### ISSUE TITLE
Provide a hashtag option for conferences

### ISSUE THREAD

**Issue by DragonBe** [afilina/phpug-data#46]
I've seen that most conferences use hashtags to track social engagements and each year they organize it, they often update their base tag with the year of the conference (e.g. #phpbnl16, #ssphp15, …)

Maybe it would be nice to include those tags in conference information as this can be useful to cross-reference social mentiones and media taken at those conferences.

Just an :bulb:

**Comment by EliW** [comment]
I think her original statement was: "Feel free to add fields".  So I think you can just 'go for it' :)

**Comment by DragonBe** [comment]
It's JSON, yes I could do that… but it's nicer to ask for permission first.

**Comment by afilina** [comment]
Great idea! I think "hashtag" under individual events would be great. Prefixing the value with "#" will avoid confusion, just like with the twitter handle.
