### ISSUE TITLE
Location radius search does not find my group

### ISSUE THREAD

**Issue by elstamey** [afilina/phpug-data#61]
I entered Raleigh, NC and 1000km as the search radius in order to see nearby meetups, and my event wasn't included:

https://community.confoo.ca/events/v/107

I am wondering if it is the () wrapping the address of the event location, or the format of the data coming from meetup.com.  

Reporting this issue here with the intention of looking more closely after work.  However, if someone else knows an answer, I welcome help!

**Comment by afilina** [comment]
Ok I fixed the algorithm for fetching user group coordinates. Here you can see it within 100km radius: https://community.confoo.ca/events/t?type=ug&min_date=&max_date=&location=Raleigh%252C+NC&radius=100&cfp_status=&s=

The two are different projects. This one is open source, the other is not. I created an issue tracker for the other project here: https://github.com/afilina/confoo-community

**Comment by elstamey** [comment]
Thanks! I really like this interface!
